---
# Copyright 2016 Internet Solutions (Pty) Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# (c) 2016 Donovan Francesco <donovan.francesco@is.co.za>
# (c) 2016 Paul Stevens <paul.stevens@is.co.za>

# We set the python interpreter to the ansible runtime venv if
# the delegation is to localhost so that we get access to the
# appropriate python libraries in that venv. If the delegation
# is to another host, we assume that it is accessible by the
# system python instead.
- name: Setup the service
  delegate_to: "{{ monasca_service_setup_host }}"
  vars:
    ansible_python_interpreter: >-
      {{ (monasca_service_setup_host == 'localhost') | ternary(ansible_playbook_python, ansible_python['executable']) }}
  block:
    - name: Add service to the keystone service catalog
      os_keystone_service:
        cloud: default
        state: present
        name: "{{ monasca_service_name }}"
        service_type: "{{ monasca_service_type }}"
        description: "{{ monasca_service_description }}"
        endpoint_type: admin
        verify: "{{ not keystone_service_adminuri_insecure }}"
      register: add_service
      until: add_service is success
      retries: 5
      delay: 10

    - name: Add service users
      os_user:
        cloud: default
        state: present
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        domain: default
        default_project: "{{ item.default_project }}"
        endpoint_type: admin
        verify: "{{ not keystone_service_adminuri_insecure }}"
      register: add_service
      when: not monasca_service_in_ldap | bool
      until: add_service is success
      retries: 5
      delay: 10
      no_log: True
      with_items:
        - name: "{{ monasca_service_user_name }}"
          password: "{{ monasca_service_password }}"
          default_project: "{{ monasca_service_project_name }}"
        - name: "{{ monasca_agent_user_name }}"
          password: "{{ monasca_agent_password }}"
          default_project: "{{ monasca_agent_project_name }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Add monasca user, agent and read only roles
      os_keystone_role:
        cloud: default
        state: present
        name: "{{ item }}"
        endpoint_type: admin
        verify: "{{ not keystone_service_adminuri_insecure }}"
      register: add_service
      when: not monasca_service_in_ldap | bool
      until: add_service is success
      retries: 5
      delay: 10
      with_flattened:
        - "{{ monasca_user_roles }}"
        - "{{ monasca_agent_roles }}"
        - "{{ monasca_read_only_user_roles }}"

    - name: Add service user to admin role
      os_user_role:
        cloud: default
        state: present
        user: "{{ monasca_service_user_name }}"
        role: "{{ monasca_role_name }}"
        project: "{{ monasca_service_project_name }}"
        endpoint_type: admin
        verify: "{{ not keystone_service_adminuri_insecure }}"
      register: add_service
      when: not monasca_service_in_ldap | bool
      until: add_service is success
      retries: 5
      delay: 10

    - name: Add agent user to agent roles
      os_user_role:
        cloud: default
        state: present
        user: "{{ monasca_agent_user_name }}"
        role: "{{ item }}"
        project: "{{ monasca_agent_project_name }}"
        endpoint_type: admin
        verify: "{{ not keystone_service_adminuri_insecure }}"
      register: add_service
      when: not monasca_service_in_ldap | bool
      until: add_service is success
      retries: 5
      delay: 10
      with_items: "{{ monasca_agent_roles }}"

    - name: Add admin user to user roles
      os_user_role:
        cloud: default
        state: present
        user: "{{ keystone_admin_user_name }}"
        role: "{{ item }}"
        project: "{{ keystone_admin_tenant_name }}"
        endpoint_type: admin
        verify: "{{ not keystone_service_adminuri_insecure }}"
      register: add_service
      when: not monasca_service_in_ldap | bool
      until: add_service is success
      retries: 5
      delay: 10
      with_items: "{{ monasca_user_roles }}"

    - name: Add endpoints to keystone endpoint catalog
      os_keystone_endpoint:
        cloud: default
        state: present
        service: "{{ monasca_service_name }}"
        endpoint_interface: "{{ item.interface }}"
        url: "{{ item.url }}"
        region: "{{ monasca_service_region }}"
        endpoint_type: admin
        verify: "{{ not keystone_service_adminuri_insecure }}"
      register: add_service
      until: add_service is success
      retries: 5
      delay: 10
      with_items:
        - interface: "public"
          url: "{{ monasca_service_publicurl }}"
        - interface: "internal"
          url: "{{ monasca_service_internalurl }}"
        - interface: "admin"
          url: "{{ monasca_service_adminurl }}"
